// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltiEG2oXmqm5Wvo28rBT8jo2nI5VVpmM',
    appId: '1:645398008589:android:176740773a921a70a6d644',
    messagingSenderId: '645398008589',
    projectId: 'live-sharing-location-app',
    databaseURL: 'https://live-sharing-location-app-default-rtdb.firebaseio.com',
    storageBucket: 'live-sharing-location-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lQ_kLEV3Waknt7kl5S7EyIPRA6HznRA',
    appId: '1:645398008589:ios:5cf6b3cd7ea54aeca6d644',
    messagingSenderId: '645398008589',
    projectId: 'live-sharing-location-app',
    databaseURL: 'https://live-sharing-location-app-default-rtdb.firebaseio.com',
    storageBucket: 'live-sharing-location-app.appspot.com',
    iosClientId: '645398008589-7b2jfatsds8qijgtd8uk81cb8ef6qvcu.apps.googleusercontent.com',
    iosBundleId: 'com.khoatransoftware.continuousTrackingApp',
  );
}
